[package]
authors = ["eric.harris-braun@holo.host"]
edition = "2021"
name = "hc_zome_syn_integrity"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_syn_integrity"

[dependencies]
serde = "1"

hdi = { workspace = true }
