[package]
authors = ["guillem.cordoba@gmail.com"]
edition = "2021"
name = "hc_zome_syn_coordinator"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_syn_coordinator"

[dependencies]
derive_more = "0.99.9"
hdk = "0.0.151"
serde = "=1.0.136"
chrono = { version = "0.4.22", default-features = false, features = ["clock", "std", "oldtime", "serde"], optional = true }

hc_zome_syn_integrity = {path = "../integrity"}